<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $appName }} — Test PDF Document</title>
    <style>
        @page {
            size: A4;
            margin: 20mm;
        }

        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            font-family: "DejaVu Sans", Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #1a202c;
        }

        .header {
            border-bottom: 3px solid #1a365d;
            padding-bottom: 16px;
            margin-bottom: 32px;
            text-align: center;
        }

        .header h1 {
            margin: 0 0 8px;
            font-size: 22pt;
            color: #1a365d;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .header .subtitle {
            margin: 0;
            font-size: 10pt;
            color: #718096;
            letter-spacing: 0.08em;
            text-transform: uppercase;
        }

        .badge {
            display: block;
            padding: 14px 24px;
            background: #ebf8ff;
            border: 2px solid #bee3f8;
            border-radius: 6px;
            text-align: center;
            margin: 24px 0;
        }

        .badge .status {
            font-size: 14pt;
            font-weight: bold;
            color: #2b6cb0;
        }

        .badge .label {
            font-size: 9pt;
            color: #4a5568;
            text-transform: uppercase;
            letter-spacing: 0.08em;
        }

        table.info {
            width: 100%;
            border-collapse: collapse;
            margin: 24px 0;
            border: 1px solid #e2e8f0;
        }

        table.info th,
        table.info td {
            padding: 10px 14px;
            text-align: left;
            border-bottom: 1px solid #e2e8f0;
        }

        table.info th {
            width: 180px;
            background: #f7fafc;
            font-size: 9pt;
            color: #718096;
            text-transform: uppercase;
            letter-spacing: 0.06em;
        }

        table.info td {
            font-size: 10pt;
            color: #1a202c;
        }

        .section {
            margin: 28px 0;
        }

        .section h2 {
            font-size: 14pt;
            color: #1a365d;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
            margin: 0 0 14px;
        }

        .checklist {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .checklist li {
            padding: 8px 0;
            border-bottom: 1px solid #edf2f7;
            font-size: 10pt;
        }

        .check {
            font-weight: bold;
            color: #276749;
            margin-right: 8px;
        }

        .footer {
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #cbd5e1;
            font-size: 8pt;
            color: #718096;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $appName }}</h1>
        <p class="subtitle">Mail Configuration — Test Document</p>
    </div>

    <div class="badge">
        <div class="label">Status</div>
        <div class="status">PDF Generation Successful</div>
    </div>

    <table class="info">
        <tr>
            <th>Organization</th>
            <td>{{ $orgName }}</td>
        </tr>
        <tr>
            <th>Generated At</th>
            <td>{{ now()->format('F j, Y g:i A') }}</td>
        </tr>
        <tr>
            <th>Environment</th>
            <td>{{ app()->environment() }}</td>
        </tr>
        <tr>
            <th>Document Type</th>
            <td>Email Attachment Test</td>
        </tr>
    </table>

    <div class="section">
        <h2>Verification Checklist</h2>
        <ul class="checklist">
            <li><span class="check">✓</span>SMTP mail server configured</li>
            <li><span class="check">✓</span>Email successfully sent with attachment</li>
            <li><span class="check">✓</span>PDF generated via spatie/laravel-pdf</li>
            <li><span class="check">✓</span>Attachment delivered intact</li>
        </ul>
    </div>

    <div class="section">
        <h2>Notes</h2>
        <p>
            This PDF document was generated dynamically and attached to a test email to verify
            the complete mail delivery pipeline, including attachment handling. If you can read
            this document, the PDF generation service, SMTP configuration, and attachment transport
            are all functioning correctly.
        </p>
    </div>

    <div class="footer">
        <p>Generated by {{ $appName }} &bull; {{ $orgName }} &bull; &copy; {{ date('Y') }} All rights reserved.</p>
    </div>
</body>
</html>
