[program:station-default]
process_name = %(program_name)s_%(process_num)s
command = php /app/artisan station:work redis --queue=default,assessments --workers=3 --memory=512 --timeout=60 --tries=1
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 120

[program:station-pdf]
process_name = %(program_name)s_%(process_num)s
command = php /app/artisan station:work redis-pdf --queue=pdf-generation --workers=2 --memory=2048 --timeout=3600 --tries=1
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 3660

[include]
files = /etc/supervisord.conf
